# Generated by Django 3.0.3 on 2020-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, verbose_name='아이디')),
                ('title', models.CharField(max_length=200, verbose_name='인원수')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name='요청사항')),
                ('reservation_date', models.DateField(verbose_name='예약날자')),
                ('reservation_time', models.TimeField(verbose_name='예약시간')),
                ('author', models.CharField(blank=True, max_length=20, verbose_name='승인여부(작성하지마세요)')),
            ],
        ),
        migrations.CreateModel(
            name='Img_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('estimation', models.CharField(max_length=10, verbose_name='평점')),
                ('image', models.ImageField(upload_to='images/', verbose_name='사진')),
                ('description', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
